{
  "name": "Debian with XFCE and VNC",
  "image": "debian:bullseye",
  "portsAttributes": {
    "5901": {
      "label": "VNC",
      "onAutoForward": "openBrowser"
    },
    "6080": {
      "label": "noVNC",
      "onAutoForward": "openBrowser"
    }
  },
  "extensions": [
    "ms-vscode-remote.remote-containers"
  ],
  "settings": {},
  "postCreateCommand": "apt-get update && apt-get install -y xfce4 x11vnc xvfb curl git"
}
