version: '3.8'

services:
  debian-vnc:
    image: dorowu/ubuntu-desktop-lxde-vnc  # Можешь заменить на свой образ, например, Debian
    ports:
      - "5901:5901"  # Порт для VNC
      - "6080:6080"  # Порт для noVNC
    environment:
      - VNC_PASSWORD=yourpassword  # Установи пароль для VNC
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: always
